### ISSUE TITLE
Survey Question on the For loop in source file 00_graph_bench/src/algorithms/openmp/triangleCount.c line 433

### ISSUE THREAD

**Issue by kishorev22** [atmughrabi/OpenGraphSim#1]
Hello Sir/ Madam
We are from a research group at Iowa State University, USA. We want to do a survey on Github developers on the methods they used for paralleling their code. To do the survey, We want to ask three questions:

1. Have you ever tried to add pragma for that 'for' loop?.

2. How much confidence do you have about the correctness of this implementation? You can choose from 1-5 with 1 as the lowest confidence score and 5 as the highest confidence.

3. (Optional) Do you actually run (interpret the code with compilation and pass input/get output) the code? Yes/No
- If yes, can you provide the information of what are the input and expected output of this program (the input that caused the program to run through this for-loop).

The for loop is from line 433 of file https:/github.com/atmughrabi/OpenGraphSim/blob/master/00_graph_bench/src/algorithms/openmp/triangleCount.c
Here is a part of the code:

nan
for (u = 0; u < graph->num_vertices; u++)
{
  uint32_t degree_u = graph->vertices->out_degree[u];
  uint32_t edge_idx_u = graph->vertices->edges_idx[u];
  uint32_t v;
  for (v = edge_idx_u; v < (edge_idx_u + degree_u); v++)
  {
    uint32_t node_v = ((uint32_t) graph->sorted_edges_array->edges_array_dest[v]) & 0x3FFFFFFF;
    if (node_v > u)
      break;

    uint32_t degree_v = graph->vertices->out_degree[node_v];
    uint32_t edge_idx_v = graph->vertices->edges_idx[node_v];
    uint32_t w;
   

Sincerely thanks

**Comment by atmughrabi** [comment]
Hello @kishorev22,

Thank you for considering this project in your survey, but this request should not be posted in the issues section. If you need any assistance feel free to email me at atmughrabi@gmail.com.

Best,
Abdullah
